/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module tester_rom_7 (
    input [4:0] address,
    output reg [59:0] testcase
  );
  
  
  
  localparam TESTADD = 120'hffff8000007fff2800000010080011;
  
  localparam TESTSUB = 120'h80007fff0100012ffffffff0100004;
  
  localparam TESTMUL = 120'hffff020002fe0030000ffff0200004;
  
  localparam TESTBOOL = 240'h555511111a55550ffff555516aaaa1ffff00001effff1ffffffff18ffff1;
  
  localparam TESTSHIFT = 300'hffff001f23ffff1ffffffff2100010ffff001f2100010ffffffff2080001ffff001f2080001;
  
  localparam TESTCOMP = 180'h555555553700010555555553500004555555553300013;
  
  localparam TESTS = 1140'h555555553700010555555553500004555555553300013ffff001f23ffff1ffffffff2100010ffff001f2100010ffffffff2080001ffff001f2080001555511111a55550ffff555516aaaa1ffff00001effff1ffffffff18ffff1ffff020002fe0030000ffff020000480007fff0100012ffffffff0100004ffff8000007fff2800000010080011000000000000000;
  
  always @* begin
    testcase = TESTS[(address)*60+59-:60];
  end
endmodule
