/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_slowclock_value;
  counter_1 slowclock (
    .clk(clk),
    .rst(rst),
    .value(M_slowclock_value)
  );
  
  wire [16-1:0] M_plus_one_out;
  seq_plus_one_2 plus_one (
    .clk(M_slowclock_value),
    .rst(rst),
    .out(M_plus_one_out)
  );
  
  wire [16-1:0] M_mult_p;
  reg [16-1:0] M_mult_a;
  reg [16-1:0] M_mult_b;
  sixteen_bit_multiplier_3 mult (
    .a(M_mult_a),
    .b(M_mult_b),
    .p(M_mult_p)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_4 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_mult_a = M_plus_one_out;
    M_mult_b[0+0-:1] = 1'h0;
    M_mult_b[1+0-:1] = 1'h1;
    M_mult_b[2+13-:14] = 15'h0000;
    io_led[0+7-:8] = M_mult_p[0+7-:8];
    io_led[8+7-:8] = M_mult_p[8+7-:8];
  end
endmodule
