/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mux_4_14 (
    input [1:0] s,
    input a,
    input b,
    input c,
    input d,
    output reg out
  );
  
  
  
  reg x;
  
  reg y;
  
  always @* begin
    
    case (s[0+0-:1])
      1'h0: begin
        x = a;
        y = c;
      end
      1'h1: begin
        x = b;
        y = d;
      end
      default: begin
        x = a;
        y = c;
      end
    endcase
    
    case (s[1+0-:1])
      1'h0: begin
        out = x;
      end
      1'h1: begin
        out = y;
      end
      default: begin
        out = x;
      end
    endcase
  end
endmodule
